name: wcu_orthodox
description: "WCU Gibi Gubae — Official Wachemo University Ethiopian Orthodox Tewahedo Church (EOTC) Student Fellowship Management, Spiritual Family Matching, Pilgrimage & Mutual Aid Platform."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.4
  fl_chart: ^1.2.0
  url_launcher: ^6.3.2
  intl: ^0.20.3
  shared_preferences: ^2.3.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "asset/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/fonts/

  fonts:
    - family: NotoSansEthiopic
      fonts:
        - asset: asset/fonts/NotoSansEthiopic-Regular.ttf
        - asset: asset/fonts/NotoSansEthiopic-Bold.ttf
          weight: 700
    - family: serif
      fonts:
        - asset: asset/fonts/NotoSansEthiopic-Regular.ttf
        - asset: asset/fonts/NotoSansEthiopic-Bold.ttf
          weight: 700
