part of 'fellowship_state.dart';

extension MockDataSeeder on FellowshipState {
  void _seedDemoData() {
    // 1. Initial Students
    _allStudents = [
      _currentUser,
      UserModel(
        id: 'usr-1',
        fullName: 'Dawit Alemu',
        baptismalName: 'Gebre Michael',
        phoneNumber: '+251911223344',
        batchYear: '2025',
        department: 'Engineering',
        academicYear: 2,
        attendancePercentage: 92.0,
        ministryStatus: 'Diaconia Volunteer',
        assignedFamilyId: 'fam-st-george',
      ),
      UserModel(
        id: 'usr-2',
        fullName: 'Hewan Bekele',
        baptismalName: 'Walata Petros',
        phoneNumber: '+251922334455',
        batchYear: '2024',
        department: 'Law',
        academicYear: 3,
        attendancePercentage: 86.0,
        ministryStatus: 'Hospitality Team',
        assignedFamilyId: 'fam-st-george',
      ),
      UserModel(
        id: 'usr-3',
        fullName: 'Sarah Jenkins',
        baptismalName: 'Walata Maryam',
        phoneNumber: '+251933445566',
        batchYear: '2025',
        department: 'Medicine & Health',
        academicYear: 2,
        attendancePercentage: 68.0, // At-risk
        ministryStatus: 'General Fellow',
        assignedFamilyId: 'fam-st-george',
      ),
      UserModel(
        id: 'usr-4',
        fullName: 'Alex Smith',
        baptismalName: 'Gebre Sellassie',
        phoneNumber: '+251944556677',
        batchYear: '2023',
        department: 'Computer Science',
        academicYear: 4,
        attendancePercentage: 95.0,
        ministryStatus: 'Media & Sound',
        assignedFamilyId: 'fam-st-george',
      ),
      UserModel(
        id: 'usr-5',
        fullName: 'Michael Kim',
        baptismalName: 'Gebre Eyesus',
        phoneNumber: '+251955667788',
        batchYear: '2025',
        department: 'Business & Economics',
        academicYear: 2,
        attendancePercentage: 71.0, // At-risk
        ministryStatus: 'General Fellow',
        assignedFamilyId: 'fam-st-tekle',
      ),
      UserModel(
        id: 'usr-6',
        fullName: 'Jane Doe',
        baptismalName: 'Kidan Maryam',
        phoneNumber: '+251966778899',
        batchYear: '2024',
        department: 'Engineering',
        academicYear: 3,
        attendancePercentage: 89.0,
        ministryStatus: 'Yaredic Choir',
        assignedFamilyId: 'fam-st-tekle',
      ),
      UserModel(
        id: 'usr-7',
        fullName: 'David Brown',
        baptismalName: 'Gebre Giorgis',
        phoneNumber: '+251977889900',
        batchYear: '2026',
        department: 'Natural Sciences',
        academicYear: 1,
        attendancePercentage: 64.0, // At-risk
        ministryStatus: 'General Fellow',
        assignedFamilyId: 'fam-st-tekle',
      ),
    ];

    // Pending Approvals Queue
    _pendingApprovals = [
      UserModel(
        id: 'usr-p1',
        fullName: 'Yared Tesfaye',
        baptismalName: 'Habte Mariam',
        phoneNumber: '+251911882233',
        batchYear: '2026',
        department: 'Civil Engineering',
        academicYear: 1,
        isApproved: false,
      ),
      UserModel(
        id: 'usr-p2',
        fullName: 'Selamawit Tilahun',
        baptismalName: 'Wolete Kidan',
        phoneNumber: '+251922993344',
        batchYear: '2026',
        department: 'Pharmacy',
        academicYear: 1,
        isApproved: false,
      ),
      UserModel(
        id: 'usr-p3',
        fullName: 'Kidus Yohannes',
        baptismalName: 'Yohannes',
        phoneNumber: '+251933004455',
        batchYear: '2025',
        department: 'Information Tech',
        academicYear: 2,
        isApproved: false,
      ),
    ];

    // 2. Orthodox Families
    _families = [
      FamilyModel(
        id: 'fam-st-george',
        name: 'Family of St. George',
        formedDate: 'Formed Sept 2023',
        spiritualFather: SpiritualParentModel(
          id: 'sp-1',
          fullName: 'Ephrem Tadesse',
          baptismalName: 'Gebre Kristos',
          department: 'Theology Department',
          faculty: 'Faculty of Theology & Tradition',
          phoneNumber: '+251911554433',
          roleTitle: 'Spiritual Father',
        ),
        spiritualMother: SpiritualParentModel(
          id: 'sp-2',
          fullName: 'Lidia Solomon',
          baptismalName: 'Wolete Mariam',
          department: 'Medical Faculty',
          faculty: 'College of Health Sciences',
          phoneNumber: '+251922665544',
          roleTitle: 'Spiritual Mother',
        ),
        maxCapacity: 10,
        telegramGroupUrl: 'https://t.me/WCU_StGeorge_Family',
        whatsappGroupUrl: 'https://chat.whatsapp.com/sample_st_george',
        isPublished: true,
        memberIds: ['usr-current', 'usr-1', 'usr-2', 'usr-3', 'usr-4'],
      ),
      FamilyModel(
        id: 'fam-st-tekle',
        name: 'Family of St. Teklehaimanot',
        formedDate: 'Formed Oct 2023',
        spiritualFather: SpiritualParentModel(
          id: 'sp-3',
          fullName: 'Johnathan Samuel',
          baptismalName: 'Tekle Tsion',
          department: 'Computer Science',
          faculty: 'Faculty of Informatics',
          phoneNumber: '+251933776655',
          roleTitle: 'Spiritual Father',
        ),
        spiritualMother: SpiritualParentModel(
          id: 'sp-4',
          fullName: 'Sara Berhanu',
          baptismalName: 'Kristos Samra',
          department: 'Economics',
          faculty: 'Business & Economics',
          phoneNumber: '+251944887766',
          roleTitle: 'Spiritual Mother',
        ),
        maxCapacity: 10,
        telegramGroupUrl: 'https://t.me/WCU_StTekle_Family',
        whatsappGroupUrl: 'https://chat.whatsapp.com/sample_st_tekle',
        isPublished: true,
        memberIds: ['usr-5', 'usr-6', 'usr-7'],
      ),
    ];

    // 3. Live Attendance Session
    _activeSession = AttendanceSessionModel(
      sessionId: 'sess-orth301',
      courseName: 'Patristics & Church History (የነገረ አበው ትምህርት)',
      courseCode: 'ORTH-301: Patristics & Church History',
      faculty: 'Orthodox Fellowship Education Department',
      code: 'ORTH-301-2026-8421',
      rollingPin: '8421',
      generatedAt: DateTime.now(),
      refreshIntervalSeconds: 30,
      totalEnrolled: 50,
      scans: [
        AttendanceRecordModel(
          id: 'rec-1',
          studentId: 'usr-6',
          studentName: 'Jane Doe',
          timestamp: DateTime.now().subtract(const Duration(minutes: 18)),
          status: AttendanceStatus.present,
          method: AttendanceCheckInMethod.qr,
          courseName: 'Patristics & Church History',
        ),
        AttendanceRecordModel(
          id: 'rec-2',
          studentId: 'usr-4',
          studentName: 'Alex Smith',
          timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
          status: AttendanceStatus.present,
          method: AttendanceCheckInMethod.pin,
          courseName: 'Patristics & Church History',
        ),
        AttendanceRecordModel(
          id: 'rec-3',
          studentId: 'usr-5',
          studentName: 'Michael Kim',
          timestamp: DateTime.now().subtract(const Duration(minutes: 12)),
          status: AttendanceStatus.present,
          method: AttendanceCheckInMethod.qr,
          courseName: 'Patristics & Church History',
        ),
        AttendanceRecordModel(
          id: 'rec-4',
          studentId: 'usr-3',
          studentName: 'Sarah Jenkins',
          timestamp: DateTime.now().subtract(const Duration(minutes: 10)),
          status: AttendanceStatus.late,
          method: AttendanceCheckInMethod.pin,
          courseName: 'Patristics & Church History',
        ),
        AttendanceRecordModel(
          id: 'rec-5',
          studentId: 'usr-1',
          studentName: 'Dawit Alemu',
          timestamp: DateTime.now().subtract(const Duration(minutes: 8)),
          status: AttendanceStatus.present,
          method: AttendanceCheckInMethod.qr,
          courseName: 'Patristics & Church History',
        ),
        AttendanceRecordModel(
          id: 'rec-6',
          studentId: 'usr-2',
          studentName: 'Hewan Bekele',
          timestamp: DateTime.now().subtract(const Duration(minutes: 5)),
          status: AttendanceStatus.present,
          method: AttendanceCheckInMethod.qr,
          courseName: 'Patristics & Church History',
        ),
        AttendanceRecordModel(
          id: 'rec-7',
          studentId: 'usr-7',
          studentName: 'David Brown',
          timestamp: DateTime.now().subtract(const Duration(minutes: 2)),
          status: AttendanceStatus.late,
          method: AttendanceCheckInMethod.pin,
          courseName: 'Patristics & Church History',
        ),
      ],
    );

    // 4. Course Roadmaps
    _roadmaps = [
      RoadmapPhaseModel(
        id: 'phase-1',
        title: 'Foundations of Faith',
        description: 'An introduction to Orthodox theology, the Nicene Creed, and the structural beauty of the Divine Liturgy.',
        status: RoadmapStatus.completed,
        progress: 1.0,
        instructor: 'Dn. Ephrem Tadesse',
        batchYear: '2024',
        semester: 'Semester 1',
        weeklyLessons: [
          LessonModel(
            id: 'l1',
            title: 'Week 1: The Nicene-Constantinopolitan Creed',
            summary: 'Comprehensive line-by-line exposition of the 12 articles of Christian Orthodox belief.',
            readingList: ['Creed Commentary - St. Athanasius', 'Faith of the 318 Fathers'],
            isDownloaded: true,
          ),
          LessonModel(
            id: 'l2',
            title: 'Week 2: Order of the Divine Liturgy',
            summary: 'Understanding the Preparatory rites, Anaphora of the Apostles, and Eucharistic communion.',
            readingList: ['Serate Kidase Manual', 'Liturgical Theology Notes'],
            isDownloaded: true,
          ),
        ],
      ),
      RoadmapPhaseModel(
        id: 'phase-2',
        title: 'Patristics',
        description: 'Deep dive into the writings of the Early Church Fathers, desert spirituality, and ascetic practice.',
        status: RoadmapStatus.inProgress,
        progress: 0.45,
        instructor: 'Memhir Yohannes Kidan',
        batchYear: '2024',
        semester: 'Semester 2',
        prerequisites: ['Foundations of Faith'],
        weeklyLessons: [
          LessonModel(
            id: 'l3',
            title: 'Week 1: St. Athanasius on the Incarnation',
            summary: 'Exegesis of De Incarnatione Verbi Dei and victory over death.',
            readingList: ['On the Incarnation Chapters 1-4', 'St. Cyril Letters to Nestorius'],
            isDownloaded: false,
          ),
          LessonModel(
            id: 'l4',
            title: 'Week 2: The Desert Fathers & Asceticism',
            summary: 'Sayings of Abba Anthony, Macarius, and monastic spirituality in Christian fellowship.',
            readingList: ['Apophthegmata Patrum', 'Spiritual Ladder of St. John Climacus'],
            isDownloaded: false,
          ),
          LessonModel(
            id: 'l5',
            title: 'Week 3: Haymanote Abew (Faith of the Fathers)',
            summary: 'Compilation of patristic homilies and Christology preserved in Ge\'ez tradition.',
            readingList: ['Haymanote Abew Homily 12-18'],
            isDownloaded: false,
          ),
        ],
      ),
      RoadmapPhaseModel(
        id: 'phase-3',
        title: 'Church Tradition & Canon Law',
        description: 'Understanding iconology, hymnography (St. Yared), fasts, and the living tradition passed down through generations.',
        status: RoadmapStatus.locked,
        progress: 0.0,
        instructor: 'Dr. Lidia Solomon',
        batchYear: '2025',
        semester: 'Semester 1',
        prerequisites: ['Patristics'],
        weeklyLessons: [
          LessonModel(
            id: 'l6',
            title: 'Week 1: St. Yaredic Musical Notation & Deggua',
            summary: 'Introduction to Geez, Ezel, and Araray modes and Ethiopian hymnology.',
            readingList: ['Tsome Deggua Guide', 'Life of St. Yared'],
            isDownloaded: false,
          ),
        ],
      ),
      RoadmapPhaseModel(
        id: 'phase-4',
        title: 'Orthodox Dogmatics & Apologetics',
        description: 'Systematic theology, Holy Sacraments (Misteerat), and answering contemporary philosophical queries.',
        status: RoadmapStatus.locked,
        progress: 0.0,
        instructor: 'Archpriest Gebre Meskel',
        batchYear: '2025',
        semester: 'Semester 2',
        prerequisites: ['Church Tradition & Canon Law'],
        weeklyLessons: [],
      ),
    ];

    // 5. Digital Library (With Direct Telegram Links!)
    _libraryItems = [
      LibraryItemModel(
        id: 'lib-1',
        title: 'The Faith of the Fathers',
        subtitle: 'Haymanote Abew (ሃይማኖተ አበው)',
        description: 'A foundational compilation of theological treatises and homilies from the early Church Fathers, carefully preserved in Ge\'ez and translated for modern university study.',
        category: LibraryCategory.patristics,
        tags: ['Patristics', 'Ge\'ez / Amharic', 'Theology'],
        telegramUrl: 'https://t.me/WCU_Orthodox_Library/101',
        sourceUrl: 'https://t.me/WCU_Orthodox_Library',
        readTime: '45 mins reading',
        coverAssetPath: 'asset/screen5 - Copy.png',
      ),
      LibraryItemModel(
        id: 'lib-2',
        title: 'Wudase Mariam',
        subtitle: 'Daily Praises of St. Mary (ውዳሴ ማርያም)',
        description: 'Traditional 7-day liturgical praises composed by St. Ephrem the Syrian with commentary by Abba Giyorgis of Gasicha.',
        category: LibraryCategory.liturgical,
        tags: ['Amharic', 'Liturgical', 'Daily Prayer'],
        telegramUrl: 'https://t.me/WCU_Orthodox_Library/102',
        sourceUrl: 'https://t.me/WCU_Orthodox_Library',
        readTime: '20 mins daily',
      ),
      LibraryItemModel(
        id: 'lib-3',
        title: 'The Divine Liturgy',
        subtitle: 'Kidase Text with Parallel Translations (መጽሐፈ ቅዳሴ)',
        description: 'The complete order of the Divine Liturgy including the 14 Eucharistic Anaphoras with side-by-side Ge\'ez, Amharic, and English translations.',
        category: LibraryCategory.liturgical,
        tags: ['Ge\'ez / Eng', 'Liturgical', 'Sacraments'],
        telegramUrl: 'https://t.me/WCU_Orthodox_Library/103',
        sourceUrl: 'https://t.me/WCU_Orthodox_Library',
        readTime: '90 mins',
      ),
      LibraryItemModel(
        id: 'lib-4',
        title: 'Mezmur Compilation',
        subtitle: 'Tsome Digua & Yaredic Hymns (ፃመ ድጓ እና ዝማሬ)',
        description: 'Spiritual audio hymns and chants composed in ancient liturgical modes by St. Yared, cataloged for fellowship choirs and individual prayer.',
        category: LibraryCategory.mezmur,
        tags: ['Audio', 'Mezmur', 'St. Yared'],
        telegramUrl: 'https://t.me/WCU_Orthodox_Library/104',
        sourceUrl: 'https://t.me/WCU_Orthodox_Library',
        audioDuration: '38 mins',
        lyricsOrExcerpts: 'በስመ አብ ወወልድ ወመንፈስ ቅዱስ አሐዱ አምላክ\nምስጋና ለቅድስት ድንግል ማርያም ይሁን...',
      ),
      LibraryItemModel(
        id: 'lib-5',
        title: 'Intro to Dogma',
        subtitle: 'Year 1 Fellowship Course Material',
        description: 'Comprehensive introduction to the 5 Pillars of Mystery (Misteerate Bete Christian): Trinity, Incarnation, Baptism, Holy Eucharist, Resurrection.',
        category: LibraryCategory.dogma,
        tags: ['English', 'Dogma', 'Academic'],
        telegramUrl: 'https://t.me/WCU_Orthodox_Library/105',
        sourceUrl: 'https://t.me/WCU_Orthodox_Library',
        readTime: '30 mins module',
      ),
    ];

    // 6. Church Programs & Feasts
    _programs = [
      ChurchProgramModel(
        id: 'prog-1',
        title: 'Upcoming Sunday Divine Liturgy',
        churchName: 'St. Mary\'s Orthodox Church',
        dateTime: DateTime.now().add(const Duration(hours: 2, minutes: 15)),
        initialDurationRemaining: const Duration(hours: 2, minutes: 15, seconds: 45),
        description: 'Solemn Kidase gathering for WCU university students with morning sermon and Eucharistic communion.',
        category: 'Liturgy',
      ),
      ChurchProgramModel(
        id: 'prog-2',
        title: 'Feast of Saint George (Lideta Giorgis)',
        churchName: 'Debre Menkrat Saint George Church',
        dateTime: DateTime.now().add(const Duration(days: 3)),
        initialDurationRemaining: const Duration(days: 3),
        description: 'Annual feast celebration with nighttime vigil (Mahlet) and fellowship agape banquet.',
        category: 'Feast',
      ),
      ChurchProgramModel(
        id: 'prog-3',
        title: 'Mid-Week Prayer & Bible Study Feed',
        churchName: 'Campus Fellowship Hall',
        dateTime: DateTime.now().add(const Duration(days: 1)),
        initialDurationRemaining: const Duration(days: 1),
        description: 'Deep study of the Epistle to the Romans with Father Ephrem Tadesse.',
        category: 'Bible Study',
      ),
    ];

    // 7. 10 Official EOTC Fellowship Departments (የግቢ ጉባኤ 10ሩ ንዑሳን ክፍሎች)
    _ministries = [
      MinistryModel(
        id: 'dept-apostolic',
        titleEn: 'Education & Apostolic Ministry',
        titleAmharic: 'ትምህርትና ሐዋርያዊ አገልግሎት',
        iconName: 'menu_book',
        descriptionEn: 'Organizes orthodox dogma courses, campus evangelism, patristics study circles, and scripture preaching.',
        descriptionAmharic: 'የነገረ መለኮት፣ የቤተክርስቲያን ታሪክና የቀኖና ትምህርቶችን ማዘጋጀት፣ ሐዋርያዊ አገልግሎትና የመጽሐፍ ቅዱስ ጥናት መርሐ ግብራትን ማስተባበር።',
        pillar: MinistryPillar.spiritualEducation,
        teamLead: 'Yared Tadesse',
        coordinatorBaptismalName: 'Gebre Meskel',
        coordinatorPhone: '+251911223344',
        coordinatorRole: 'Apostolic Ministry Coordinator',
        openSlots: 8,
        activeCount: 34,
        tags: ['Dogma', 'Evangelism', 'Bible Study', 'Patristics'],
        subWings: [
          'Dogmatics & Canon (ነገረ መለኮት)',
          'Scripture Study (የመጽሐፍ ቅዱስ ጥናት)',
          'Apostolic Outreach (ሐዋርያዊ ስብከት)',
          'Patristics & Library (የአበው ታሪክ)',
        ],
        meetingSchedule: 'Tuesdays 5:30 PM & Sundays 2:00 PM',
        requirements: 'Foundational church course completion; dedicated heart for gospel teaching.',
      ),
      MinistryModel(
        id: 'dept-membercare',
        titleEn: 'Member Care, Counseling & Capacity',
        titleAmharic: 'አባላት እንክብካቤ ፤ምክክርና አቅም ማጎልበቻ',
        iconName: 'favorite_border',
        descriptionEn: 'Follows up on students spiritual and moral well-being, conducts peer counseling, and organizes leadership workshops.',
        descriptionAmharic: 'የተማሪዎችን መንፈሳዊና ማኅበራዊ ሕይወት መከታተል፣ የምክር አገልግሎት መስጠት እና የአመራር ክህሎት ማጎልበቻ ስልጠናዎችን ማዘጋጀት።',
        pillar: MinistryPillar.memberCareSocial,
        teamLead: 'Selamawit Desta',
        coordinatorBaptismalName: 'Walata Maryam',
        coordinatorPhone: '+251922334455',
        coordinatorRole: 'Member Care Coordinator',
        openSlots: 6,
        activeCount: 28,
        tags: ['Care', 'Counseling', 'Freshmen', 'Leadership'],
        subWings: [
          'Freshman Follow-up (የአዳዲስ ተማሪዎች ክትትል)',
          'Spiritual Counseling (የምክርና ማጽናናት)',
          'Capacity Building (የአቅም ማጎልበቻ)',
          'Sisterhood Care (የእህቶች ሕብረት)',
        ],
        meetingSchedule: 'Thursdays 6:00 PM',
        requirements: 'Empathy, confidentiality, and active commitment to fellowship life.',
      ),
      MinistryModel(
        id: 'dept-music',
        titleEn: 'Music & Arts',
        titleAmharic: 'መዝሙርና ስነ ጥበባት',
        iconName: 'music_note',
        descriptionEn: 'Prepares spiritual hymns, liturgical chants (Zema), sacred Begena/Kirar instruments, Christian drama, and iconography.',
        descriptionAmharic: 'የኦርቶዶክሳዊ ዝማሬዎችን ማጥናት፣ የበገናና ክራር ትምህርት፣ መንፈሳዊ ድራማ፣ ስነ ጽሑፍ እና ስዕለ አድኅኖ ስነ ጥበባት።',
        pillar: MinistryPillar.spiritualEducation,
        teamLead: 'Dawit Fikadu',
        coordinatorBaptismalName: 'Gebre Yohannes',
        coordinatorPhone: '+251933445566',
        coordinatorRole: 'Music & Arts Coordinator',
        openSlots: 12,
        activeCount: 52,
        tags: ['Mezmur', 'Zema', 'Begena', 'Drama', 'Poetry'],
        subWings: [
          'Choir Vocal & Zema (የዝማሬና ዜማ ዘርፍ)',
          'Begena & Instruments (የበገናና መሳሪያዎች)',
          'Spiritual Drama (መንፈሳዊ ቴአትር)',
          'Literature & Poetry (ስነ ጽሑፍና ስንኝ)',
        ],
        meetingSchedule: 'Wednesdays & Saturdays 4:00 PM',
        requirements: 'Punctual rehearsal attendance; dedication to ancient Yaredic traditions.',
      ),
      MinistryModel(
        id: 'dept-development',
        titleEn: 'Development & Revenue Collection',
        titleAmharic: 'ልማትና ገቢ አሰባሰብ',
        iconName: 'monetization_on_outlined',
        descriptionEn: 'Plans and coordinates fundraising initiatives, holiday sales, spiritual publications distribution, and donor campaigns.',
        descriptionAmharic: 'የገቢ ማስገኛ ፕሮጀክቶችን መንደፍ፣ የበዓላት ባዛርና የንዋየ ቅድሳት ሽያጭ ማስተባበር፣ የበጎ አድራጊዎች ድጋፍ ማሰባሰብ።',
        pillar: MinistryPillar.operationsFinance,
        teamLead: 'Ermias Berhanu',
        coordinatorBaptismalName: 'Habte Maryam',
        coordinatorPhone: '+251944556677',
        coordinatorRole: 'Development Coordinator',
        openSlots: 5,
        activeCount: 22,
        tags: ['Fundraising', 'Bazaar', 'Alumni', 'Projects'],
        subWings: [
          'Fundraising Projects (የገቢ ፕሮጀክቶች)',
          'Holiday Bazaars & Sales (የበዓላት ባዛር)',
          'Alumni Relations (የቀድሞ ተማሪዎች)',
          'Merchandise & Books (የመጻሕፍትና ንዋያተ ቅድሳት)',
        ],
        meetingSchedule: 'Fridays 5:00 PM',
        requirements: 'Project management, marketing creativity, or sales enthusiasm.',
      ),
      MinistryModel(
        id: 'dept-accounting',
        titleEn: 'Accounting & Property',
        titleAmharic: 'ሒሳብና ንብረት',
        iconName: 'account_balance_wallet',
        descriptionEn: 'Maintains meticulous accounting ledgers, manages fellowship assets, sound systems, robes, and campus church property.',
        descriptionAmharic: 'የፋይናንስና የሂሳብ መዛግብትን መያዝ፣ የድምፅ መሳሪያዎችን፣ አልባሳትና የግብረ ጽድቅ ንብረቶችን በአግባቡ ማስተዳደር።',
        pillar: MinistryPillar.operationsFinance,
        teamLead: 'Bethlehem Girma',
        coordinatorBaptismalName: 'Walata Tsion',
        coordinatorPhone: '+251955667788',
        coordinatorRole: 'Accounting & Property Coordinator',
        openSlots: 4,
        activeCount: 16,
        tags: ['Finance', 'Ledger', 'Audio Gear', 'Inventory'],
        subWings: [
          'Bookkeeping & Finance (የሂሳብ መዝገብ)',
          'Sound & Audio Equipment (የድምፅ መሳሪያዎች)',
          'Church Vestments & Robes (የአልባሳት ንብረት)',
          'Procurement & Logistics (ግዢና አቅርቦት)',
        ],
        meetingSchedule: 'Saturdays 10:00 AM',
        requirements: 'High integrity and diligence; Accounting/Economics background preferred.',
      ),
      MinistryModel(
        id: 'dept-programs',
        titleEn: 'Batch & Program Coordination',
        titleAmharic: 'ባችና መርሐ ግብራት ማስተባበሪያ',
        iconName: 'event_available',
        descriptionEn: 'Coordinates year batches (1st to graduating class), reserves campus auditoriums, and manages overall fellowship schedules.',
        descriptionAmharic: 'የየክፍለ ዓመቱን (የባች) ተወካዮች ማስተባበር፣ የአዳራሽና የቦታ ፈቃድ ማመቻቸት፣ ሳምንታዊና ወርሃዊ መርሐ ግብራትን ማቀናጀት።',
        pillar: MinistryPillar.memberCareSocial,
        teamLead: 'Abel Solomon',
        coordinatorBaptismalName: 'Tekle Haymanot',
        coordinatorPhone: '+251966778899',
        coordinatorRole: 'Batch & Programs Coordinator',
        openSlots: 7,
        activeCount: 30,
        tags: ['Batch Reps', 'Hall Booking', 'Conferences', 'Events'],
        subWings: [
          'Freshman Batch Reps (የ1ኛ ዓመት ተወካዮች)',
          'Senior & Graduating Reps (የተመራቂዎች)',
          'Hall Booking & Protocol (የአዳራሽና ፕሮቶኮል)',
          'Vigil & Feast Logistics (የጉባኤያት አቀነባባሪ)',
        ],
        meetingSchedule: 'Mondays 6:00 PM',
        requirements: 'Punctuality, strong organizational communication across batches.',
      ),
      MinistryModel(
        id: 'dept-charity',
        titleEn: 'Vocational & Charitable Activities',
        titleAmharic: 'ሙያ ና በጎ አድራጎት',
        iconName: 'volunteer_activism',
        descriptionEn: 'Manages student mutual aid, hospital & orphanage visits, blood drives, dorm welfare visits, and vocational peer tutoring.',
        descriptionAmharic: 'ለተቸገሩ ተማሪዎች የምግብና የትምህርት ድጋፍ ማድረግ፣ የሆስፒታልና የአቅመ ደካሞች ጥየቃ፣ የደም ልገሳና የሙያ ማጋራት።',
        pillar: MinistryPillar.memberCareSocial,
        teamLead: 'Rahel Tesfaye',
        coordinatorBaptismalName: 'Walata Michael',
        coordinatorPhone: '+251977889900',
        coordinatorRole: 'Charity Coordinator',
        openSlots: 10,
        activeCount: 40,
        tags: ['Charity', 'Mutual Aid', 'Hospital Visit', 'Blood Drive'],
        subWings: [
          'Student Emergency Fund (የተማሪዎች ድጋፍ)',
          'Hospital & Prison Outreach (የሕሙማን ጥየቃ)',
          'Community Blood Drive (የደም ልገሳ)',
          'Vocational Tutoring (የትምህርትና ሙያ ማጋራት)',
        ],
        meetingSchedule: 'Saturdays 2:00 PM',
        requirements: 'Compassionate heart for charity, active attendance in welfare visits.',
      ),
      MinistryModel(
        id: 'dept-language',
        titleEn: 'Language & Special Needs',
        titleAmharic: 'ቋንቋና ልዩ ልዩ ፍላጎት',
        iconName: 'translate',
        descriptionEn: 'Provides multilingual liturgical services (Afan Oromo, Tigrinya, English), sign language translation, and accessibility for disabled members.',
        descriptionAmharic: 'በተለያዩ ቋንቋዎች (በአፋን ኦሮሞ፣ በትግርኛ፣ በእንግሊዝኛ) ትምህርቶችን ማዘጋጀት፣ የምልክት ቋንቋ አገልግሎትና አካል ጉዳተኞችን ማገዝ።',
        pillar: MinistryPillar.spiritualEducation,
        teamLead: 'Gemechu Bekele',
        coordinatorBaptismalName: 'Haile Maryam',
        coordinatorPhone: '+251988990011',
        coordinatorRole: 'Language & Special Needs Coordinator',
        openSlots: 8,
        activeCount: 25,
        tags: ['Afan Oromo', 'Sign Language', 'Tigrinya', 'English', 'Inclusion'],
        subWings: [
          'Afan Oromo Ministry (የአፋን ኦሮሞ አገልግሎት)',
          'Tigrinya & Other Languages (የትግርኛና ሌሎች)',
          'Sign Language (የምልክት ቋንቋ)',
          'Accessibility Support (የልዩ ፍላጎት ድጋፍ)',
        ],
        meetingSchedule: 'Sundays 4:00 PM',
        requirements: 'Language fluency or willingness to learn sign language.',
      ),
      MinistryModel(
        id: 'dept-planning',
        titleEn: 'Planning & Monitoring',
        titleAmharic: 'እቅድና ክትትል',
        iconName: 'insights',
        descriptionEn: 'Prepares semester/annual strategic plans, tracks project KPIs, monitors department execution, and evaluates performance.',
        descriptionAmharic: 'የግቢ ጉባኤውን ዓመታዊና ሴሚስተራዊ እቅድ ማዘጋጀት፣ የክፍላትን አፈፃፀም መከታተልና የግምገማ ሪፖርቶችን ማቅረብ።',
        pillar: MinistryPillar.governanceAudit,
        teamLead: 'Nahom Assefa',
        coordinatorBaptismalName: 'Gebre Kidan',
        coordinatorPhone: '+251999001122',
        coordinatorRole: 'Planning & Monitoring Coordinator',
        openSlots: 3,
        activeCount: 14,
        tags: ['Strategy', 'KPIs', 'Reports', 'Evaluation'],
        subWings: [
          'Strategic Planning (የስትራቴጂክ እቅድ)',
          'Department Tracking (የክፍላት አፈፃፀም)',
          'Statistical Analysis (የስታቲስቲክስ ትንተና)',
          'Evaluation Seminars (የግምገማ መድረኮች)',
        ],
        meetingSchedule: 'Sundays 6:00 PM',
        requirements: 'Analytical thinking, organizational discipline, 2nd year or above.',
      ),
      MinistryModel(
        id: 'dept-audit',
        titleEn: 'Audit & Inspection',
        titleAmharic: 'ኦዲት ና ኢንስፔክሽን',
        iconName: 'fact_check_outlined',
        descriptionEn: 'Conducts independent financial audits, verifies property registries, and ensures adherence to EOTC fellowship bylaws and canons.',
        descriptionAmharic: 'ገለልተኛ የፋይናንስና የሂሳብ ምርመራ ማካሄድ፣ የንብረት ቆጠራና ማረጋገጫ፣ የደንብና መመሪያ ተገዢነትን መቆጣጠር።',
        pillar: MinistryPillar.governanceAudit,
        teamLead: 'Kaleb Worku',
        coordinatorBaptismalName: 'Wolde Rufael',
        coordinatorPhone: '+251910112233',
        coordinatorRole: 'Audit & Inspection Coordinator',
        openSlots: 3,
        activeCount: 12,
        tags: ['Audit', 'Finance Check', 'Inventory Audit', 'Compliance'],
        subWings: [
          'Financial Audit (የፋይናንስ ቁጥጥር)',
          'Asset Inspection (የንብረት ፍተሻ)',
          'Bylaw Compliance (የመተዳደሪያ ደንብ)',
          'Quarterly Reports (የሩብ ዓመት ሪፖርት)',
        ],
        meetingSchedule: 'Bi-weekly Saturdays 9:00 AM',
        requirements: 'Uncompromising integrity, 3rd/4th year student, background in Accounting/Law/Management.',
      ),
    ];

    // Seeded Department Members (Active Servants with Dual Choir Leadership)
    _departmentMembers = [
      DepartmentMemberModel(
        id: 'mem-1',
        departmentId: 'dept-music',
        studentId: 'usr-101',
        studentName: 'Dawit Fikadu',
        studentBaptismalName: 'Gebre Yohannes',
        studentDept: 'Civil Engineering',
        studentYear: '4th Year',
        phoneNumber: '+251933445566',
        subWing: 'Choir Vocal & Zema (የዝማሬና ዜማ ዘርፍ)',
        choirWing: ChoirWingType.mezmur,
        roleInDepartment: 'Mezmur Section Lead (የመዝሙር ክፍል ኃላፊ)',
        joinedDate: DateTime.now().subtract(const Duration(days: 300)),
      ),
      DepartmentMemberModel(
        id: 'mem-2',
        departmentId: 'dept-music',
        studentId: 'usr-102',
        studentName: 'Martha Tedla',
        studentBaptismalName: 'Walata Petros',
        studentDept: 'Medicine',
        studentYear: '4th Year',
        phoneNumber: '+251922556677',
        subWing: 'Spiritual Drama & Arts (መንፈሳዊ ቴአትርና ስነ ጥበባት)',
        choirWing: ChoirWingType.fineArts,
        roleInDepartment: 'Fine Arts Section Lead (የስነ ጥበባት ክፍል ኃላፊ)',
        joinedDate: DateTime.now().subtract(const Duration(days: 280)),
      ),
      DepartmentMemberModel(
        id: 'mem-3',
        departmentId: 'dept-accounting',
        studentId: 'usr-103',
        studentName: 'Amanuel Tadesse',
        studentBaptismalName: 'Gebre Gabriel',
        studentDept: 'Accounting & Finance',
        studentYear: '3rd Year',
        phoneNumber: '+251933667788',
        subWing: 'Bookkeeping & Finance (የሂሳብ መዝገብ)',
        roleInDepartment: 'Assistant Auditor',
        joinedDate: DateTime.now().subtract(const Duration(days: 90)),
      ),
      DepartmentMemberModel(
        id: 'mem-4',
        departmentId: 'dept-charity',
        studentId: 'usr-104',
        studentName: 'Hanna Solomon',
        studentBaptismalName: 'Walata Maryam',
        studentDept: 'Nursing',
        studentYear: '2nd Year',
        phoneNumber: '+251944778899',
        subWing: 'Hospital & Prison Outreach (የሕሙማን ጥየቃ)',
        roleInDepartment: 'Hospital Visit Lead',
        joinedDate: DateTime.now().subtract(const Duration(days: 120)),
      ),
    ];

    // Seeded Volunteer Applications routed to coordinators
    _volunteerApplications = [
      VolunteerApplicationModel(
        id: 'app-sample-1',
        studentId: 'usr-1',
        studentName: 'Dawit Alemu',
        studentBaptismalName: 'Gebre Michael',
        studentDept: 'Electrical Engineering',
        studentPhone: '+251911223344',
        studentYear: '2nd Year',
        ministryId: 'dept-music',
        ministryTitle: 'Music & Arts',
        ministryAmharicTitle: 'መዝሙርና ስነ ጥበባት',
        preferredSubWing: 'Choir Vocal & Zema (የዝማሬና ዜማ ዘርፍ)',
        choirWing: ChoirWingType.mezmur,
        reason: 'I have been learning traditional Begena hymnody for 2 years and wish to serve in campus spiritual nights.',
        experience: 'Parish youth choir Begena player in Debre Markos',
        availability: 'Wednesday evenings & Sunday afternoons',
        status: ApplicationStatus.pending,
        appliedAt: DateTime.now().subtract(const Duration(hours: 3)),
      ),
      VolunteerApplicationModel(
        id: 'app-sample-2',
        studentId: 'usr-2',
        studentName: 'Hewan Bekele',
        studentBaptismalName: 'Walata Petros',
        studentDept: 'Accounting & Finance',
        studentPhone: '+251922334455',
        studentYear: '3rd Year',
        ministryId: 'dept-accounting',
        ministryTitle: 'Accounting & Property',
        ministryAmharicTitle: 'ሒሳብና ንብረት',
        preferredSubWing: 'Bookkeeping & Finance (የሂሳብ መዝገብ)',
        reason: 'Eager to apply my accounting skills to ensure transparent, audited fellowship property and ledgers.',
        experience: 'Accounting student, familiarity with Excel & Peachtree',
        availability: 'Saturdays & Friday afternoons',
        status: ApplicationStatus.pending,
        appliedAt: DateTime.now().subtract(const Duration(hours: 6)),
      ),
      VolunteerApplicationModel(
        id: 'app-sample-3',
        studentId: 'usr-3',
        studentName: 'Mikias Haile',
        studentBaptismalName: 'Gebre Kristos',
        studentDept: 'Pharmacy',
        studentPhone: '+251933445566',
        studentYear: '1st Year Freshman',
        ministryId: 'dept-charity',
        ministryTitle: 'Vocational & Charitable Activities',
        ministryAmharicTitle: 'ሙያ ና በጎ አድራጎት',
        preferredSubWing: 'Student Emergency Fund (የተማሪዎች ድጋፍ)',
        reason: 'I want to help needy freshman students adapt to university life and coordinate meal ticket support.',
        experience: 'Red Cross high school volunteer leader',
        availability: 'Saturdays and free afternoons',
        status: ApplicationStatus.approved,
        appliedAt: DateTime.now().subtract(const Duration(days: 2)),
        reviewedAt: DateTime.now().subtract(const Duration(days: 1)),
        reviewedByCoordinator: 'Rahel Tesfaye (Charity Coordinator)',
        coordinatorNotes: 'Welcome aboard Mikias! Please join the Saturday 2:00 PM briefing.',
      ),
      VolunteerApplicationModel(
        id: 'app-sample-4',
        studentId: 'usr-4',
        studentName: 'Tolosa Dibaba',
        studentBaptismalName: 'Gebre Yesus',
        studentDept: 'Law',
        studentPhone: '+251955112233',
        studentYear: '3rd Year',
        ministryId: 'dept-language',
        ministryTitle: 'Language & Special Needs',
        ministryAmharicTitle: 'ቋንቋና ልዩ ልዩ ፍላጎት',
        preferredSubWing: 'Afan Oromo Ministry (የአፋን ኦሮሞ አገልግሎት)',
        languagesKnown: ['Afan Oromo', 'Amharic', 'English'],
        reason: 'Passionate about translating patristic catechism and Sunday hymns into Afan Oromo for campus freshmen.',
        experience: 'Youth fellowship translator for 3 years',
        availability: 'Sundays after Liturgy & Tuesday evenings',
        status: ApplicationStatus.pending,
        appliedAt: DateTime.now().subtract(const Duration(hours: 8)),
      ),
    ];

    // Seeded Department Broadcast Messages
    _departmentBroadcasts = [
      DepartmentBroadcastMessageModel(
        id: 'dmsg-1',
        departmentId: FellowshipDepartmentConstants.deptEducation,
        title: '🌟 ልዩ የስብከተ ወንጌል መርሐ ግብር - መጋቤ ሐዲስ ዶ/ር ሮዳስ ታደሰ',
        body: 'በመጪው እሑድ ከቀኑ 9:00 ጀምሮ በዋናው አዳራሽ ልዩ የአባቶች ታሪክና አስደናቂ የስነ-ፍጥረት ትምህርት ይሰጣል። ሁሉም የግቢው ተማሪዎች እንዲገኙ ተጋብዘዋል።',
        senderName: 'Mulugeta Assefa',
        senderRole: 'Education Coordinator',
        sentAt: DateTime.now().subtract(const Duration(days: 1)),
        urgency: 'meeting',
        targetBatch: 'all',
        targetAudienceLabel: 'All Students (ሁሉንም ተማሪዎች)',
        broadcastCategory: 'specialProgram',
        instructorOrSpeaker: 'መጋቤ ሐዲስ ዶ/ር ሮዳስ ታደሰ',
        meetingLocation: 'WCU Main Auditorium Hall A',
        meetingTime: DateTime.now().add(const Duration(days: 3, hours: 4)),
      ),
      DepartmentBroadcastMessageModel(
        id: 'dmsg-edu-2',
        departmentId: FellowshipDepartmentConstants.deptEducation,
        title: '📖 የ2ኛ ዓመት የሃይማኖተ አበው (Patristics) የፈተና መርሐ ግብር ማሳሰቢያ',
        body: 'የ2ኛ ዓመት ባች ተማሪዎች የሃይማኖተ አበው አጋማሽ ፈተና በሚቀጥለው ማክሰኞ 12:30 በክፍል 402 ይሰጣል። እባካችሁ በሰዓቱ ተገኙ።',
        senderName: 'Mulugeta Assefa',
        senderRole: 'Education Coordinator',
        sentAt: DateTime.now().subtract(const Duration(hours: 6)),
        urgency: 'urgent',
        targetBatch: '2',
        targetAudienceLabel: 'Year 2 Batch (2ኛ ዓመት ባች)',
        broadcastCategory: 'courseInfo',
        courseCode: 'PATR-201',
        instructorOrSpeaker: 'መምህር ዮሐንስ ኪዳን',
      ),
      DepartmentBroadcastMessageModel(
        id: 'dmsg-2',
        departmentId: FellowshipDepartmentConstants.deptChoirArts,
        title: '🎼 አስቸኳይ የመዝሙርና የድራማ ልምምድ ጥሪ',
        body: 'ለመስቀል በዓል ዝግጅት የመዝሙርና የስነ ጥበባት አባላት ቅዳሜ ከቀኑ 8:30 ጀምሮ በቤተክርስቲያኑ አዳራሽ እንድትገኙ።',
        senderName: 'Dawit Fikadu',
        senderRole: 'Choir & Arts Coordinator',
        sentAt: DateTime.now().subtract(const Duration(hours: 12)),
        urgency: 'meeting',
        targetBatch: 'all',
        targetAudienceLabel: 'All Choir Members',
        broadcastCategory: 'generalNotice',
        meetingLocation: 'Campus Chapel Youth Hall',
        meetingTime: DateTime.now().add(const Duration(days: 2)),
      ),
      DepartmentBroadcastMessageModel(
        id: 'dmsg-3',
        departmentId: FellowshipDepartmentConstants.deptDevelopment,
        title: '💼 የገቢ አሰባሰብ ፕሮፖዛል ለሥራ አስፈፃሚ ቀርቧል',
        body: 'የ2017 ዓመታዊ የበዓላት ባዛርና የንዋያተ ቅድሳት ኤግዚቢሽን ፕሮፖዛል ለአድሚን ቦርድ ቀርቦ ፀድቋል። ዝርዝር የስራ ክፍፍል በቅርቡ ይገለጻል።',
        senderName: 'Ermias Berhanu',
        senderRole: 'Development Coordinator',
        sentAt: DateTime.now().subtract(const Duration(days: 2)),
        urgency: 'normal',
        targetBatch: 'all',
        targetAudienceLabel: 'All Fellowship Members',
        broadcastCategory: 'generalNotice',
      ),
    ];

    // Seeded Fundraising Proposals (DEPT_DEVELOPMENT)
    _fundraisingProposals = [
      FundraisingProposalModel(
        id: 'prop-1',
        title: 'የ2017 ዓመታዊ ታላቁ የበዓላት ባዛርና የንዋያተ ቅድሳት ሽያጭ',
        objective: 'ለተማሪዎች መንፈሳዊ ጉዞ እና ለተቸገሩ አባላት የዕለት ድጋፍ የሚውል ገቢ ማሰባሰብ።',
        targetAmount: 75000.0,
        expectedExpenses: 8000.0,
        proposedStrategy: 'የበዓላት ዳቦና ሻማ ሽያጭ፣ የኦርቶዶክሳዊ መጻሕፍትና መዛሙርት አውደ ርዕይ፣ የፎቶ ማስታወሻዎች።',
        targetAudience: 'የግቢው ተማሪዎች፣ መምህራንና የከተማው ኦርቶዶክሳውያን ምዕመናን',
        category: 'Bazaar & Exhibition (ባዛርና አውደ ርዕይ)',
        timelineOrDuration: '2 Weeks (Meskerem 14 - 28)',
        submittedByName: 'Ermias Berhanu',
        submittedAt: DateTime.now().subtract(const Duration(days: 4)),
        status: ProposalStatus.approved,
        adminReviewNotes: 'ታላቅ እቅድ ነው፤ የቦታ ፈቃድ ከግቢው አስተዳደር ጋር ተነጋግረን አጠናቀናል። ተፈቅዷል!',
        reviewedAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
      FundraisingProposalModel(
        id: 'prop-2',
        title: 'የቀድሞ ተማሪዎች (Alumni Fellowship) የቋሚ ድጋፍ ፈንድ',
        objective: 'ከተመረቁ የቀድሞ የግቢ ጉባኤ አባላት ጋር ኔትወርክ በመፍጠር ወርሃዊ የድጋፍ ስምምነት መመስረት።',
        targetAmount: 120000.0,
        expectedExpenses: 3500.0,
        proposedStrategy: 'የቴሌግራም ቦትና የባንክ ቋሚ ትእዛዝ (Standing Order) በማዘጋጀት ወርሃዊ የ100 ብር አባልነት ማስተባበር።',
        targetAudience: 'በመላው ሀገሪቱ የሚገኙ የቀድሞ ዋቸሞ ግቢ ጉባኤ ተመራቂዎች',
        category: 'Alumni Pledge (የቀድሞ ተማሪዎች ድጋፍ)',
        timelineOrDuration: 'Ongoing Semester Campaign (ሴሚስተር)',
        submittedByName: 'Ermias Berhanu',
        submittedAt: DateTime.now().subtract(const Duration(hours: 18)),
        status: ProposalStatus.pending,
      ),
      FundraisingProposalModel(
        id: 'prop-3',
        title: 'የቅዱሳት ሥዕላትና የመዝሙር ሲዲዎች አውደ ርዕይ',
        objective: 'ለግቢ ጉባኤው ቤተ መጻሕፍት ማስፋፊያ እና ድምፅ ማጉያ ዕቃዎች ግዢ የሚውል ፈንድ ማሰባሰብ።',
        targetAmount: 45000.0,
        expectedExpenses: 4000.0,
        proposedStrategy: 'በግቢው ካምፓስ ዋና መተላለፊያ ላይ የሥነ ጥበብ አውደ ርዕይ በማዘጋጀት ሽያጭ ማካሄድ።',
        targetAudience: 'የዩኒቨርሲቲው ተማሪዎችና የከተማ ምዕመናን',
        category: 'Sacred Artifacts (የንዋያተ ቅድሳት ሽያጭ)',
        timelineOrDuration: '3 Days (Tikimt 5 - 7)',
        submittedByName: 'Ermias Berhanu',
        submittedAt: DateTime.now().subtract(const Duration(days: 6)),
        status: ProposalStatus.rejected,
        adminReviewNotes: 'የቦታ ፈቃድ ደብዳቤ ከዩኒቨርሲቲው ዲን ገና ስላልተፈረመ፣ ፈቃዱ ሲያልቅ እንደገና እንዲቀርብ።',
        reviewedAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
    ];

    // 8. Liturgical Calendar & Fasting Engine (Dynamic Live Ethiopian Calendar 2017+ E.C.)
    _calendarWeek = EthiopianCalendarHelper.generateWeek();
    _currentCalendarDay = EthiopianCalendarHelper.fromGregorian(DateTime.now());

    // 9. Daily Prayer Book (Wudase Maryam & Yezewetir Tselot)
    _wudaseMaryam = const PrayerBookModel(
      id: 'bk-wudase',
      title: 'Wudase Maryam (Praise of St. Mary)',
      titleGeEz: 'ውዳሴ ማርያም (ዘሰባቱ ዕለታት)',
      description: 'Daily praises composed by St. Ephrem the Syrian and St. Cyriacus of Behnesa.',
      sections: [
        PrayerSectionModel(
          id: 'wud-mon',
          titleGeEz: 'ውዳሴ ዘሰኑይ (ሰኞ)',
          titleAmharic: 'የሰኞ ውዳሴ ማርያም',
          titleEn: 'Monday Praises of St. Mary',
          geEzText: '''ፈቀደ እግዚእ ያግዕዞ ለአዳም ኅዙነ ወትኩዘ ልብ፡ ወያግብኦ ኀበ ዘቀዳሚ መንበሩ።
አክሊለ ሠነይትኪ ኦ ድንግል ንጽሕት።
ተፈሥሒ ኦ ድንግል ንጽሕት ዘአልቦታ ሙስና፡ ዘተወልደ እምኔኪ አምላከ ቅዱሳን።
ዘአልቦ ጥንት ወዘአልቦ ማኅለቅት ዘከማሁ።
እስመ ውእቱ አክበረኪ ወአልዐለኪ እምኩሉ ፍጥረት።
ኪሩቤል ወሱራፌል ይሰግዱ ለኪ ወይዌድሱኪ በዕለተ ዕረፍት።''',
          amharicText: '''ጌታ ልቡ ያዘነና የተከዘ አዳምን ነፃ ያወጣው ዘንድ፥ ወደ ቀደመ ቦታውም ይመልሰው ዘንድ ወደደ።
ንጽሕት ድንግል ሆይ፥ መልካም አክሊላችን አንቺ ነሽ።
ጥፋት የሌለብሽ ንጽሕት ድንግል ሆይ ደስ ይበልሽ፤ ከአንቺ የተወለደው የቅዱሳን አምላክ ነው።
እርሱ መጀመሪያና መጨረሻ የሌለው ነው።
ከፍጡራን ሁሉ በላይ አክብሮሻልና፥ ከፍ ከፍም አድርጎሻልና።
ኪሩቤልና ሱራፌል በሰንበት ቀን ይሰግዱልሻል፥ ያመሰግኑሻልም።''',
        ),
        PrayerSectionModel(
          id: 'wud-tue',
          titleGeEz: 'ውዳሴ ዘሠሉስ (ማክሰኞ)',
          titleAmharic: 'የማክሰኞ ውዳሴ ማርያም',
          titleEn: 'Tuesday Praises of St. Mary',
          geEzText: '''አክሊለ ምክሕነ ወቀዳሚተ መድኃኒትነ፡ ወመሠረተ ንጽሕነ ኮነ በማርያም ድንግል፡ እንተ ወለደት ለነ ዘእግዚአብሔር ቃለ።
ዘኮነ ሰብአ በእንተ መድኃኒትነ።
እምድኅረ ኮነ ሰብአ ፈጸመ ኩሎ ሕገ ወትእዛዘ።
ዘአልቦ ኃጢአት ወዘኢረከበ ቦቱ ዐመፃ።
ተፈሥሒ ኦ ማርያም ድንግል ዘተፀነሰ በማኅፀንኪ መድኅነ ዓለም።''',
          amharicText: '''የመመኪያችን ዘውድ፥ የመዳናችን መጀመሪያ፥ የንጽሕናችን መሠረት የእግዚአብሔርን ቃል በወለደችልን በድንግል ማርያም ሆነ።
እርሱ ስለ እኛ መዳን ሰው ሆነ።
ሰው ከሆነም በኋላ ሕግንና ትእዛዝን ሁሉ ፈጸመ።
ኃጢአት የሌለበትና በደል ያልተገኘበት ነው።
የዓለም መድኃኒት በማኅፀንሽ የተፀነሰ ድንግል ማርያም ሆይ ደስ ይበልሽ።''',
        ),
        PrayerSectionModel(
          id: 'wud-wed',
          titleGeEz: 'ውዳሴ ዘረቡዕ (ረቡዕ)',
          titleAmharic: 'የረቡዕ ውዳሴ ማርያም',
          titleEn: 'Wednesday Praises of St. Mary',
          geEzText: '''ኩሉ ሠራዊተ ሰማያት ይብሉ ብፅዕት አንቲ፡ ታቦት ንጽሕት ዘአልቦታ ርኩስ።
ዘአስተርአየ ውስቴታ ማኅደረ መለኮት።
አንቲ ውእቱ ደብተራ ዘተሰመይኪ ቅድስተ ቅዱሳን።
ዘውስቴታ ታቦት ዘወርቅ ጽሩይ፡ ዘአልቦታ ጥልቀት።
ጽላተ ኪዳን ዘጸሐፎን በአጻብዒሁ እግዚአብሔር።''',
          amharicText: '''የሰማይ ሠራዊት ሁሉ እድለኛ ነሽ ይላሉ፤ እድፍ ጉድፍ የሌለብሽ ንጽሕት ታቦት ነሽና።
የመለኮት ማደሪያ በእርሷ የታየባት።
ቅድስተ ቅዱሳን የተባልሽ ድንኳን አንቺ ነሽ።
በውስጧ ምንም ጉድለት የሌለበት የጠራ የወርቅ ታቦት አለ።
እግዚአብሔር በጣቶቹ የጻፋቸው የኪዳን ጽላት በውስጧ አሉ።''',
        ),
        PrayerSectionModel(
          id: 'wud-thu',
          titleGeEz: 'ውዳሴ ዘሐሙስ (ሐሙስ)',
          titleAmharic: 'የሐሙስ ውዳሴ ማርያም',
          titleEn: 'Thursday Praises of St. Mary',
          geEzText: '''ዕፀ ጳጦስ እንተ ርእያ ሙሴ በነደ እሳት እንዘ ተነድድ ወኢትውዒ፡ ማርያም ይእቲ።
ዘነደ እሳተ መለኮቱ ኢያውዓያ።
ተፈሥሒ ኦ ምልዕተ ጸጋ ዘተወልደ እምኔኪ ክርስቶስ።
ብርሃን ዘእምብርሃን፡ አምላክ ዘእምአምላክ ዘበአማን።
ወልደ እግዚአብሔር ሕያው።''',
          amharicText: '''ሙሴ በእሳት ነበልባል ስትነድድ ሳለች ያልተቃጠለች ያያት ዛፍ (ዕፀ ጳጦስ) ማርያም ናት።
የመለኮቱ እሳት ነበልባል አላቃጠላትምና።
ጸጋን የተመላሽ ሆይ ደስ ይበልሽ፤ ከአንቺ የተወለደው ክርስቶስ ነው።
ከብርሃን የተገኘ ብርሃን፥ ከእውነተኛ አምላክ የተገኘ እውነተኛ አምላክ ነው።
የሕያው እግዚአብሔር ልጅ።''',
        ),
        PrayerSectionModel(
          id: 'wud-fri',
          titleGeEz: 'ውዳሴ ዘዓርብ (ዓርብ)',
          titleAmharic: 'የዓርብ ውዳሴ ማርያም',
          titleEn: 'Friday Praises of St. Mary',
          geEzText: '''ብፅዕት አንቲ ኦ ማርያም ወቡሩክ ፍሬ ከርሥኪ።
ድንግል ማርያም ወላዲተ አምላክ።
ዘአልቦ ሙስና ወዘኢይማስን በውሳጣ።
ተፈሥሒ ኦ ቅድስት ድንግል ዘበእንቲአኪ ተሣሃለነ እግዚአብሔር።
ወአድኃነነ እምደይን።''',
          amharicText: '''ማርያም ሆይ አንቺ የተባረክሽ ነሽ፥ የማኅፀንሽም ፍሬ የተባረከ ነው።
አምላክን የወለድሽ ድንግል ማርያም ሆይ።
በውስጧ ጥፋት የሌለባትና የማትጠፋ።
ቅድስት ድንግል ሆይ ደስ ይበልሽ፤ በአንቺ ምክንያት እግዚአብሔር ይቅር አለን።
ከፍርድም አዳነን።''',
        ),
        PrayerSectionModel(
          id: 'wud-sat',
          titleGeEz: 'ውዳሴ ዘቀዳሚት (ቅዳሜ)',
          titleAmharic: 'የቅዳሜ ውዳሴ ማርያም',
          titleEn: 'Saturday Praises of St. Mary',
          geEzText: '''ቅድስት ወብፅዕት አንቲ ድንግል ማርያም፡ ታቦተ ጽድቅ ወማኅደረ ሰላም።
እስመ እምኔኪ ተወልደ ፀሐየ ጽድቅ።
ዘአብርሃ ለኩሉ ፍጥረት በብርሃነ መለኮቱ።
ተፈሥሒ ኦ ድንግል ንጽሕት ዘአስተርአየ በላዕሌኪ ስብሐተ እግዚአብሔር።''',
          amharicText: '''ድንግል ማርያም ሆይ አንቺ ቅድስትና የተመሰገንሽ ነሽ፤ የእውነት ታቦትና የሰላም ማደሪያ ነሽ።
ከአንቺ የጽድቅ ፀሐይ ተወልዷልና።
በመለኮቱ ብርሃን ለፍጥረት ሁሉ ያበራ።
የእግዚአብሔር ክብር በአንቺ ላይ የታየ ንጽሕት ድንግል ሆይ ደስ ይበልሽ።''',
        ),
        PrayerSectionModel(
          id: 'wud-sun',
          titleGeEz: 'ውዳሴ ዘእሑድ (እሑድ)',
          titleAmharic: 'የእሑድ ውዳሴ ማርያም',
          titleEn: 'Sunday Praises of St. Mary',
          geEzText: '''ይዌድስዋ መላእክት ለማርያም በውስተ መንጦላዕት፡ ወይብሉ ብፅዕት አንቲ እምኩሎን አንስት።
እስመ ተወልደ እምኔኪ መድኅነ ዓለም።
ተፈሥሒ ኦ ድንግል ምልዕተ ጸጋ፡ እግዚአብሔር ምስሌኪ።
ኪሩቤል ወሱራፌል ይሰግዱ ለኪ።''',
          amharicText: '''መላእክት በመጋረጃው ውስጥ ሆነው ማርያምን ያመሰግኗታል፤ ከሴቶች ሁሉ አንቺ የተባረክሽ ነሽ ይላሉ።
የዓለም መድኃኒት ከአንቺ ተወልዷልና።
ጸጋን የተመላሽ ድንግል ሆይ ደስ ይበልሽ፤ እግዚአብሔር ከአንቺ ጋር ነው።
ኪሩቤልና ሱራፌል ይሰግዱልሻል።''',
        ),
      ],
    );

    _yezewetirTselot = const PrayerBookModel(
      id: 'bk-yezewetir',
      title: 'Yezewetir Tselot (Daily Prayers)',
      titleGeEz: 'ጸሎት ዘዘወትር',
      description: 'Canonical Daily Prayers chanted by Orthodox faithful morning and evening.',
      sections: [
        PrayerSectionModel(
          id: 'yzt-1',
          titleGeEz: 'በስመ አብ ወወልድ ወመንፈስ ቅዱስ',
          titleAmharic: 'የመክፈቻ ጸሎት',
          titleEn: 'Introductory Trinitarian Prayer',
          geEzText: '''በስመ አብ ወወልድ ወመንፈስ ቅዱስ አሐዱ አምላክ አሜን።
ስብሐት ለአብ ስብሐት ለወልድ ስብሐት ለመንፈስ ቅዱስ።
ስብሐት ለእግዝእትነ ማርያም ድንግል ወላዲተ አምላክ።
ስብሐት ለመስቀለ ክርስቶስ ዕፀ መድኃኒት።''',
          amharicText: '''በአብ በወልድ በመንፈስ ቅዱስ አንድ አምላክ ስም አሜን።
ለአብ ምስጋና ይሁን፥ ለወልድ ምስጋና ይሁን፥ ለመንፈስ ቅዱስ ምስጋና ይሁን።
አምላክን ለወለደች ለእመቤታችን ለድንግል ማርያም ምስጋና ይሁን።
ለመድኃኒት እንጨት ለክርስቶስ መስቀል ምስጋና ይሁን።''',
        ),
        PrayerSectionModel(
          id: 'yzt-2',
          titleGeEz: 'አቡነ ዘበሰማያት',
          titleAmharic: 'የጌታ ጸሎት (አባታችን ሆይ)',
          titleEn: 'The Lord’s Prayer (Our Father)',
          geEzText: '''አቡነ ዘበሰማያት፡ ይቀደስ ስምከ፡ ትምጻእ መንግሥትከ፡ ለይኩን ፈቃድከ በከመ በሰማይ ከማሁ በምድር።
ሲሳየነ ዘለለ ዕለትነ ሀበነ ዮም፡ ኅድግ ለነ አበሳነ ወጌጋየነ በከመ ንሕነኒ ንኅድግ ለዘአበሰ ለነ።
ኢታብአነ እግዚኦ ውስተ መንሱት፡ አላ አድኅነነ ወባልሐነ እምኩሉ እኩይ።
እስመ ዚአከ ይእቲ መንግሥት ኃይል ወስብሐት ለዓለመ ዓለም አሜን።''',
          amharicText: '''በሰማያት የምትኖር አባታችን ሆይ፥ ስምህ ይቀደስ፤ መንግሥትህ ትምጣ፤ ፈቃድህ በሰማይ እንደ ሆነች እንዲሁም በምድር ትሁን።
የዕለት እንጀራችንን ዛሬ ስጠን፤ እኛም የበደሉንን ይቅር እንደምንል በደላችንን ይቅር በለን።
አቤቱ ወደ ፈተና አታግባን፥ ከክፉ ሁሉ አድነን እንጂ።
መንግሥት ያንተ ናትና ኃይልም ክብርም ለዘለዓለሙ አሜን።''',
        ),
      ],
    );

    // 10. Father Confessor & Spiritual Guidance Mock Data
    _confessorFathers = [
      ConfessorFatherModel(
        id: 'fat-1',
        fullName: 'Kesis Yohannes Teshome',
        clericalTitle: 'መልአከ ሰላም ቀሲስ (Melake Selam Kesis)',
        churchName: "St. Mary's Orthodox Church (Hosanna WCU)",
        meetingVenue: "St. Mary's Sunday School Office (Room 2)",
        phoneNumber: '+251911456789',
        availableDays: ['Wednesday', 'Saturday', 'Sunday'],
        availableTimeSlots: ['9:00 AM - 11:30 AM', '3:00 PM - 5:30 PM'],
        bio: 'Campus fellowship Confession Father with 15+ years guiding university students in repentance, prayer, and Christian discipline.',
      ),
      ConfessorFatherModel(
        id: 'fat-2',
        fullName: 'Abba Gebre Selassie',
        clericalTitle: 'ቆሞስ አባ (Komos Abba)',
        churchName: 'Debre Mewi Medhanealem Church',
        meetingVenue: 'Medhanealem Parish Library / Counseling Hall',
        phoneNumber: '+251912987654',
        availableDays: ['Thursday', 'Saturday', 'Sunday'],
        availableTimeSlots: ['2:00 PM - 4:30 PM', '5:00 PM - 7:00 PM'],
        bio: 'Spiritual director specialized in Patristic counseling, youth moral guidance, and preparation for the Holy Mysteries.',
      ),
    ];

    _confessionAppointments = [
      ConfessionAppointmentModel(
        id: 'conf-1',
        studentId: _currentUser.id,
        studentName: _currentUser.fullName,
        studentBaptismalName: _currentUser.baptismalName,
        studentPhone: _currentUser.phoneNumber,
        fatherId: 'fat-1',
        fatherName: 'መልአከ ሰላም ቀሲስ Yohannes Teshome',
        scheduledDate: DateTime.now().add(const Duration(days: 3)),
        timeSlot: '3:00 PM - 5:30 PM',
        topic: 'Communion Preparation & General Confession',
        status: ConfessionAppointmentStatus.confirmed,
        notes: 'Please read Psalm 50 (መዝሙረ ዳዊት 50) before arriving.',
      ),
    ];

    _spiritualQuestions = [
      AnonymousSpiritualQuestionModel(
        id: 'q-1',
        questionText: 'How should a university student observe fasting and prayer while having heavy laboratory and exam schedules?',
        category: 'Fasting & Campus Life',
        askedAt: DateTime.now().subtract(const Duration(days: 2)),
        isAnswered: true,
        answerText: 'Fasting is spiritual discipline combined with love and obedience. Eat nutritious vegan meals (legumes, vegetables, bread) after breaking your fast, maintain morning and evening prayer rules, and consult your Confession Father for canonical adjustments during strict exam weeks.',
        answeredBy: 'መልአከ ሰላም ቀሲስ Yohannes',
        isPublic: true,
      ),
      AnonymousSpiritualQuestionModel(
        id: 'q-2',
        questionText: 'What is the significance of receiving the Holy Eucharist with fasting from the previous midnight?',
        category: 'Sacraments & Canon',
        askedAt: DateTime.now().subtract(const Duration(days: 4)),
        isAnswered: true,
        answerText: 'Receiving the Holy Body and Blood of our Lord Jesus Christ requires complete physical and spiritual preparation (minimum 9 hours fasting, reconciliation with all brethren, sincere confession).',
        answeredBy: 'ቆሞስ አባ Gebre Selassie',
        isPublic: true,
      ),
    ];

    _communionChecklist = [
      CommunionChecklistItem(
        id: 'chk-1',
        title: 'Confession with Spiritual Father (ንስሐ መግባት)',
        description: 'Have a valid, recent confession and spiritual absolution.',
        isChecked: true,
      ),
      CommunionChecklistItem(
        id: 'chk-2',
        title: 'Reconciliation with Brethren (ከሰው ሁሉ ጋር መታረቅ)',
        description: 'Forgive anyone who wronged you and seek forgiveness from those you offended.',
        isChecked: true,
      ),
      CommunionChecklistItem(
        id: 'chk-3',
        title: '18-Hour / Midnight Fasting (የቁርባን ጾም መጠበቅ)',
        description: 'Abstain from all food and drink from midnight until Liturgy completion.',
        isChecked: false,
      ),
      CommunionChecklistItem(
        id: 'chk-4',
        title: 'Spiritual Focus & Cleanliness (ንጽሕናና ጸሎት)',
        description: 'Refrain from worldly disputes, keep pure thoughts, and recite Psalm 50.',
        isChecked: false,
      ),
    ];

    // 11. Pilgrimage & Monastery Trip Coordinator Mock Data
    _pilgrimageTrips = [
      PilgrimageTripModel(
        id: 'trip-kulubi',
        title: 'Annual Kulubi St. Gabriel Pilgrimage (የቁልቢ ቅዱስ ገብርኤል ንግሥ)',
        destination: 'Kulubi St. Gabriel Monastery (Harar Route)',
        departureDate: DateTime.now().add(const Duration(days: 14)),
        returnDate: DateTime.now().add(const Duration(days: 17)),
        departurePoint: 'WCU Main Campus Student Center Gate',
        isFree: false,
        feeAmount: 650.0,
        telebirrNumber: '+251911223344',
        telebirrAccountName: 'WCU Orthodox Student Fellowship (የተማሪዎች ግቢ ጉባኤ)',
        cbeAccountNumber: '1000234567890',
        cbeAccountName: 'WCU Orthodox Tewahedo Fellowship',
        totalSeats: 90,
        bookedSeats: 68,
        itinerary: [
          'Day 1 (Thursday 5:00 AM): Departure from WCU Gate via Awash route',
          'Day 2 (Friday): Arrival at Kulubi, Evening Mahlet & Prayer Vigil',
          'Day 3 (Saturday): Divine Liturgy (Kidase) & Holy Communion at St. Gabriel',
          'Day 4 (Sunday): Return journey and testimony sharing',
        ],
        packingList: [
          'Netela / Gabi (ነጠላ / ጋቢ)',
          'Prayer Book (የጸሎት መጽሐፍ)',
          'Warm clothing for night vigil',
          'Personal medication & water bottle',
          'WCU Student ID card',
        ],
        coordinatorName: 'Dn. Biruk Tadesse',
        coordinatorPhone: '+251911887766',
      ),
      PilgrimageTripModel(
        id: 'trip-gishen',
        title: 'Gishen Debre Kerbe Holy Cross Pilgrimage (ግሸን ደብረ ከርቤ)',
        destination: 'Gishen Mariam Holy Cross Monastery (Wollo)',
        departureDate: DateTime.now().add(const Duration(days: 28)),
        returnDate: DateTime.now().add(const Duration(days: 32)),
        departurePoint: 'WCU Main Campus Gate 1',
        isFree: false,
        feeAmount: 850.0,
        telebirrNumber: '+251911223344',
        telebirrAccountName: 'WCU Orthodox Student Fellowship',
        cbeAccountNumber: '1000234567890',
        cbeAccountName: 'WCU Orthodox Tewahedo Fellowship',
        totalSeats: 45,
        bookedSeats: 32,
        itinerary: [
          'Day 1: Departure from Hosanna via Dessie',
          'Day 2: Ascent to Gishen Amba, veneration of True Cross (ግማደ መስቀል)',
          'Day 3: Festal Kidase & blessing from Monastery elders',
          'Day 4: Safe return to campus',
        ],
        packingList: [
          'Comfortable mountain hiking shoes',
          'Netela & prayer rope',
          'Warm jacket (High altitude)',
          'Student Fellowship Pass',
        ],
        coordinatorName: 'Yared Teshome',
        coordinatorPhone: '+251922334455',
      ),
      PilgrimageTripModel(
        id: 'trip-local',
        title: 'Local Monastery Blessing & Prayer Retreat (የአካባቢ ገዳማት ጉብኝት)',
        destination: 'St. George & Debre Tsion Local Monastery (Gurage/Hosanna)',
        departureDate: DateTime.now().add(const Duration(days: 7)),
        returnDate: DateTime.now().add(const Duration(days: 7, hours: 10)),
        departurePoint: 'WCU Library Square',
        isFree: true, // Free Fellowship Trip
        feeAmount: 0.0,
        telebirrNumber: '+251911223344',
        telebirrAccountName: 'WCU Orthodox Student Fellowship',
        cbeAccountNumber: '1000234567890',
        cbeAccountName: 'WCU Orthodox Tewahedo Fellowship',
        totalSeats: 50,
        bookedSeats: 41,
        itinerary: [
          '7:00 AM: Morning bus departure',
          '8:30 AM: Liturgy & spiritual teaching with Monastery Abbot',
          '1:00 PM: Agape fellowship lunch',
          '5:00 PM: Return to WCU dormitories',
        ],
        packingList: ['Netela (ነጠላ)', 'Notebook & Bible', 'Fellowship ID'],
        coordinatorName: 'Kidanemariam Biratu',
        coordinatorPhone: '+251933445566',
      ),
    ];

    _tripRegistrations = [
      TripRegistrationModel(
        id: 'reg-sample-1',
        tripId: 'trip-local',
        tripTitle: 'Local Monastery Blessing & Prayer Retreat',
        studentId: _currentUser.id,
        studentName: _currentUser.fullName,
        studentBaptismalName: _currentUser.baptismalName,
        studentPhone: _currentUser.phoneNumber,
        department: _currentUser.department,
        academicYear: _currentUser.academicYear,
        busNumber: 1,
        seatNumber: 14,
        feeAmount: 0.0,
        isFree: true,
        paymentMethod: PaymentMethodType.free,
        transactionReference: 'FREE-ENTRY-WCU-2026',
        paymentStatus: TripPaymentStatus.free,
        qrTicketCode: 'PILGRIM-TRIP-LOCAL-USR-CURRENT',
        registeredAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      TripRegistrationModel(
        id: 'reg-sample-2',
        tripId: 'trip-kulubi',
        tripTitle: 'Annual Kulubi St. Gabriel Pilgrimage',
        studentId: 'usr-1',
        studentName: 'Dawit Alemu',
        studentBaptismalName: 'Gebre Michael',
        studentPhone: '+251911223344',
        department: 'Engineering',
        academicYear: 2,
        busNumber: 2,
        seatNumber: 22,
        feeAmount: 650.0,
        isFree: false,
        paymentMethod: PaymentMethodType.telebirr,
        transactionReference: 'TB-982347102938',
        paymentStatus: TripPaymentStatus.verified,
        qrTicketCode: 'PILGRIM-KULU-USR-1',
        registeredAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
    ];

    // 12. Student Mutual Aid & Charity Fund Mock Data
    _charityCampaigns = [
      CharityCampaignModel(
        id: 'camp-student-aid',
        title: 'Campus Student Mutual Aid & Emergency Fund (የተማሪዎች መረዳጃ ፈንድ)',
        description: 'Confidential emergency financial aid supporting fellow university students facing medical emergencies, cafeteria meal distress, and urgent travel needs.',
        targetAmount: 50000.0,
        raisedAmount: 34200.0,
        donorsCount: 142,
        deadline: DateTime.now().add(const Duration(days: 45)),
        isEmergency: true,
        category: 'Student Mutual Aid',
      ),
      CharityCampaignModel(
        id: 'camp-orphan',
        title: 'Semester Orphanage & Hospital Care Outreach (የሆስፒታልና የህፃናት ማሳደጊያ)',
        description: 'Provide hygiene supplies, books, clothing, and spiritual companionship to hospitalized patients and orphaned children in Hosanna town.',
        targetAmount: 25000.0,
        raisedAmount: 18750.0,
        donorsCount: 88,
        deadline: DateTime.now().add(const Duration(days: 20)),
        category: 'Orphanage Outreach',
      ),
    ];

    _duesPayments = [
      DuesPaymentModel(
        id: 'due-1',
        studentId: _currentUser.id,
        studentName: _currentUser.fullName,
        amount: 50.0,
        purpose: 'Monthly Fellowship Dues (የአባልነት መዋጮ)',
        paymentMethod: PaymentMethodType.telebirr,
        transactionReference: 'TB-87491028374',
        status: 'Verified',
        submittedAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      DuesPaymentModel(
        id: 'due-2',
        studentId: 'usr-senior-1',
        studentName: 'Abel Tesfaye',
        amount: 250.0,
        purpose: 'Student Mutual Aid Donation',
        paymentMethod: PaymentMethodType.cbeBirr,
        transactionReference: 'CBE-394827104',
        status: 'Verified',
        submittedAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
    ];

    _charityDisbursements = [
      CharityDisbursementModel(
        id: 'disb-1',
        beneficiaryName: 'Hewan Bekele (Year 2 Law)',
        assistanceType: 'Medical & Clinic Prescription Support',
        amount: 1200.0,
        voucherReference: 'DISB-MED-2026-08',
        approvedBy: 'Charity Coordinator',
        disbursedAt: DateTime.now().subtract(const Duration(days: 2)),
        notes: 'Disbursed via Telebirr for urgent malaria medication.',
      ),
      CharityDisbursementModel(
        id: 'disb-2',
        beneficiaryName: 'Yohannes Girma (Year 1 Engineering)',
        assistanceType: 'Cafeteria & Meal Subsidy Voucher',
        amount: 850.0,
        voucherReference: 'DISB-MEAL-2026-04',
        approvedBy: 'Charity Coordinator',
        disbursedAt: DateTime.now().subtract(const Duration(days: 6)),
        notes: 'Meal assistance voucher for needy freshman student.',
      ),
    ];

    _emergencyAidRequests = [
      EmergencyAidRequestModel(
        id: 'aid-1',
        studentId: 'usr-2',
        studentName: 'Hewan Bekele',
        studentBaptismalName: 'Walata Petros',
        studentPhone: '+251922334455',
        department: 'Law',
        academicYear: 2,
        category: EmergencyAidCategory.medical,
        description: 'Emergency prescription medication and medical exam cost following sudden malaria illness at WCU clinic.',
        amountRequested: 1200.0,
        status: EmergencyAidStatus.approved,
        submittedAt: DateTime.now().subtract(const Duration(days: 2)),
        adminNote: 'Approved by Charity Committee. Disbursed via Telebirr.',
      ),
    ];

    // 13. Department Mentorship Matching Mock Data
    _academicMentors = [
      AcademicMentorModel(
        id: 'mnt-1',
        studentId: 'usr-senior-1',
        fullName: 'Abel Tesfaye',
        baptismalName: 'Gebre Kristos',
        department: 'Computer Science',
        academicYear: 4,
        specialties: ['Data Structures & Algorithms', 'Flutter & Mobile App Dev', 'Database Systems'],
        telegramHandle: '@abel_fellowship_cs',
        phoneNumber: '+251911335577',
        activeMenteesCount: 2,
        maxMentees: 3,
        isAvailable: true,
      ),
      AcademicMentorModel(
        id: 'mnt-2',
        studentId: 'usr-senior-2',
        fullName: 'Dr. (Intern) Selamawit G/Medhin',
        baptismalName: 'Walata Maryam',
        department: 'Medicine & Health Sciences',
        academicYear: 5,
        specialties: ['Anatomy & Physiology', 'Pathology & Pharmacology', 'Clinical Study Skills'],
        telegramHandle: '@selam_med_mentor',
        phoneNumber: '+251922446688',
        activeMenteesCount: 1,
        maxMentees: 3,
        isAvailable: true,
      ),
      AcademicMentorModel(
        id: 'mnt-3',
        studentId: 'usr-senior-3',
        fullName: 'Ermias Berhanu',
        baptismalName: 'Haile Georgis',
        department: 'Civil Engineering',
        academicYear: 4,
        specialties: ['Structural Analysis', 'Fluid Mechanics', 'Engineering Mathematics'],
        telegramHandle: '@ermias_civil_wcu',
        phoneNumber: '+251933557799',
        activeMenteesCount: 2,
        maxMentees: 3,
        isAvailable: true,
      ),
      AcademicMentorModel(
        id: 'mnt-4',
        studentId: 'usr-senior-4',
        fullName: 'Mahlet Assefa',
        baptismalName: 'Kirstos Samra',
        department: 'Accounting & Finance',
        academicYear: 3,
        specialties: ['Cost Accounting', 'Financial Management', 'Business Statistics'],
        telegramHandle: '@mahlet_acct',
        phoneNumber: '+251944668800',
        activeMenteesCount: 0,
        maxMentees: 3,
        isAvailable: true,
      ),
    ];

    _mentorshipRequests = [
      MentorshipRequestModel(
        id: 'mnt-req-1',
        juniorStudentId: _currentUser.id,
        juniorName: _currentUser.fullName,
        juniorBaptismalName: _currentUser.baptismalName,
        department: _currentUser.department,
        academicYear: _currentUser.academicYear,
        mentorId: 'mnt-1',
        mentorName: 'Abel Tesfaye',
        coursesNeeded: 'Data Structures and Algorithm optimization in C++ / Dart',
        status: MentorshipStatus.matched,
        requestedAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
    ];

    // 14. Faith Challenge Trivia & Leaderboard Mock Data
    _triviaQuizzes = [
      TriviaQuizModel(
        id: 'quiz-wk-1',
        weekNumber: 1,
        title: 'Week 1: Orthodox Dogma & The Holy Trinity',
        description: 'Test your understanding of Orthodox Christology, the Trinity, and Church Traditions.',
        timeLimitMinutes: 5,
        questions: [
          TriviaQuestionModel(
            id: 'tq-1',
            questionAmharic: 'በኢትዮጵያ ኦርቶዶክስ ተዋሕዶ ቤተክርስቲያን እምነት መሠረት እግዚአብሔር በስም፣ በአካል፣ በግብር ሦስት ሲሆን በምን አንድ ነው?',
            questionEnglish: 'According to Orthodox Dogmatics, God is three in Name, Person, and Attribute. In what is God ONE?',
            options: ['በባሕርይ፣ በህልውና እና በመለኮት (In Essence, Existence & Divinity)', 'በአካል ብቻ (In Person only)', 'በግብር ብቻ (In Attribute only)', 'በስም ብቻ (In Name only)'],
            correctOptionIndex: 0,
            explanation: 'እግዚአብሔር በአንድ መለኮት፣ በአንድ ባሕርይ፣ በአንድ ፈቃድና ሥልጣን አንዲት አምላክ ነው። (Deut 6:4, John 10:30)',
            bibleReference: 'ዘዳግም 6፥4 / ዮሐንስ 10፥30',
          ),
          TriviaQuestionModel(
            id: 'tq-2',
            questionAmharic: 'የእመቤታችን ቅድስት ድንግል ማርያም የዘወትር ውዳሴ (ውዳሴ ማርያም) የደረሰው ቅዱስ አባት ማን ይባላል?',
            questionEnglish: 'Which Saint composed the daily praises of St. Mary (Wudase Maryam)?',
            options: ['ቅዱስ ኤፍሬም ሶርያዊ (St. Ephrem the Syrian)', 'ቅዱስ ዮሐንስ አፈወርቅ (St. John Chrysostom)', 'ቅዱስ ያሬድ (St. Yared)', 'ቅዱስ ዲዮስቆሮስ (St. Dioscorus)'],
            correctOptionIndex: 0,
            explanation: 'ውዳሴ ማርያምን በሰባቱ ዕለታት የደረሰው ቅዱስ ኤፍሬም ሶርያዊ ሲሆን፣ ቅዱስ ጊዮርጊስ ዘጋስቻና ሌሎችም ተቀብለውታል።',
            bibleReference: 'ሉቃስ 1፥48',
          ),
          TriviaQuestionModel(
            id: 'tq-3',
            questionAmharic: 'በኦርቶዶክስ ተዋሕዶ ቤተክርስቲያን ከሰባቱ ምሥጢራተ ቤተክርስቲያን ውስጥ የማይደገመው የትኛው ነው?',
            questionEnglish: 'Which of the Seven Sacraments cannot be repeated once received?',
            options: ['ምሥጢረ ጥምቀት (Holy Baptism)', 'ምሥጢረ ንስሐ (Holy Confession)', 'ምሥጢረ ቁርባን (Holy Eucharist)', 'ምሥጢረ ቀንዲል (Holy Unction)'],
            correctOptionIndex: 0,
            explanation: 'ጥምቀት አንዲት ናት፤ አትደገምም። “አንድ ጌታ፥ አንድ እምነት፥ አንዲት ጥምቀት” (ኤፌሶን 4፥5)።',
            bibleReference: 'ኤፌሶን 4፥5',
          ),
          TriviaQuestionModel(
            id: 'tq-4',
            questionAmharic: 'በኢትዮጵያ ኦርቶዶክስ ተዋሕዶ የቀኖና ሕግ መሠረት በዓመት ውስጥ ስንት የአዋጅ አጽዋማት አሉ?',
            questionEnglish: 'According to the Canons of the Ethiopian Orthodox Tewahedo Church, how many official fasting seasons (አጽዋማት) exist?',
            options: ['7 አጽዋማት (Seven Fasting Seasons)', '5 አጽዋማት', '3 አጽዋማት', '10 አጽዋማት'],
            correctOptionIndex: 0,
            explanation: 'ሰባቱ አጽዋማት፡ ዐቢይ ጾም፣ ጾመ ሐዋርያት፣ ጾመ ፍልሰታ፣ ጾመ ነቢያት፣ ጾመ ገሃድ፣ ጾመ ነነዌ እና የረቡዕና ዓርብ ጾም ናቸው።',
            bibleReference: 'ፍትሐ ነገሥት አንቀጽ 15',
          ),
          TriviaQuestionModel(
            id: 'tq-5',
            questionAmharic: 'በቅዳሴ ጊዜ ኅብስቱና ወይኑ ወደ ክርስቶስ ሥጋና ደም የሚለወጥበት ምሥጢር ምን ይባላል?',
            questionEnglish: 'What is the holy transformation of the bread and wine into the Body and Blood of Christ during Liturgy called?',
            options: ['ምሥጢረ ቁርባን / ተውላጦ (Holy Eucharist / Epiclesis Transformation)', 'ምሥጢረ ክህነት', 'ምሥጢረ ሜሮን', 'ምሥጢረ ተክሊል'],
            correctOptionIndex: 0,
            explanation: 'በመንፈስ ቅዱስ ኃይልና በካህኑ ጸሎት ኅብስቱ ወደ እውነተኛው የክርስቶስ ሥጋ፥ ወይኑ ወደ እውነተኛው የክርስቶስ ደም ይለወጣል።',
            bibleReference: '1 ቆሮንቶስ 11፥23-26',
          ),
        ],
      ),
    ];

    _familyLeaderboard = [
      const FamilyLeaderboardEntry(
        familyId: 'fam-st-george',
        familyName: 'Family of St. George (የቅዱስ ጊዮርጊስ ቤተሰብ)',
        totalScore: 1420,
        participantsCount: 18,
        rank: 1,
      ),
      const FamilyLeaderboardEntry(
        familyId: 'fam-st-mary',
        familyName: "Family of St. Mary (የእመቤታችን ቤተሰብ)",
        totalScore: 1280,
        participantsCount: 16,
        rank: 2,
      ),
      const FamilyLeaderboardEntry(
        familyId: 'fam-st-michael',
        familyName: 'Family of St. Michael (የቅዱስ ሚካኤል ቤተሰብ)',
        totalScore: 1150,
        participantsCount: 14,
        rank: 3,
      ),
      const FamilyLeaderboardEntry(
        familyId: 'fam-st-tekla',
        familyName: 'Family of Abune Teklehaimanot (የአቡነ ተክለሃይማኖት ቤተሰብ)',
        totalScore: 980,
        participantsCount: 12,
        rank: 4,
      ),
    ];
  }
}
