// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOW5Opx7BtLyA6s237nEqAckjuiBYUd48',
    appId: '1:624095213051:web:88994da6c1e6bf7dd6c75e',
    messagingSenderId: '624095213051',
    projectId: 'wcu-orthodox',
    authDomain: 'wcu-orthodox.firebaseapp.com',
    storageBucket: 'wcu-orthodox.firebasestorage.app',
    measurementId: 'G-E7V05KEXJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCehEa2VsvKf5RuOkBtZmKiwetp_E_VKWk',
    appId: '1:624095213051:android:c399bea4eb96797bd6c75e',
    messagingSenderId: '624095213051',
    projectId: 'wcu-orthodox',
    storageBucket: 'wcu-orthodox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEjphjzDHx6ArOoQNcR4tbBgHXD2ELs30',
    appId: '1:624095213051:ios:491b3fe2722b4a20d6c75e',
    messagingSenderId: '624095213051',
    projectId: 'wcu-orthodox',
    storageBucket: 'wcu-orthodox.firebasestorage.app',
    iosBundleId: 'com.example.wcuOrthodox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEjphjzDHx6ArOoQNcR4tbBgHXD2ELs30',
    appId: '1:624095213051:ios:491b3fe2722b4a20d6c75e',
    messagingSenderId: '624095213051',
    projectId: 'wcu-orthodox',
    storageBucket: 'wcu-orthodox.firebasestorage.app',
    iosBundleId: 'com.example.wcuOrthodox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOW5Opx7BtLyA6s237nEqAckjuiBYUd48',
    appId: '1:624095213051:web:ebb60ee28fc483d9d6c75e',
    messagingSenderId: '624095213051',
    projectId: 'wcu-orthodox',
    authDomain: 'wcu-orthodox.firebaseapp.com',
    storageBucket: 'wcu-orthodox.firebasestorage.app',
    measurementId: 'G-KJRV9L1SP1',
  );
}
